### ISSUE TITLE
Steps to run the code

### ISSUE THREAD

**Issue by sahulsumra** [abertsch72/unlimiformer#33]
Can you explain me how to run this code?

**Comment by abertsch72** [comment]
Hi @sahulsumra, thanks for your interest in our work! Have you tried following the instructions for running in the [readme](https://github.com/abertsch72/unlimiformer#getting-started)?

**Comment by patrickocal** [comment]
Hi @abertsch72, I can get the inference_example.py working fine. Working with a decent-sized gpu on the cluster, so it's fast and very happy with that.

But I had a bunch of problems with "src/run.py", when I try to run:
```
python src/run.py \
    src/configs/training/base_training_args.json \
    src/configs/data/gov_report.json \
    --output_dir output_train_bart_base_local/ \
    --learning_rate 1e-5 \
    --model_name_or_path facebook/bart-base \
    --max_source_length 1024 \
    --eval_max_source_length 1024 --do_eval=True \
    --eval_steps 1000 --save_steps 1000 \
    --per_device_eval_batch_size 1 --per_device_train_batch_size 2 \
    --extra_metrics bertscore
```
I get:
```Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/run.py", line 1180, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/run.py", line 437, in main
    seq2seq_dataset = _get_dataset(data_args, model_args, training_args)
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/run.py", line 943, in _get_dataset
    seq2seq_dataset = load_dataset(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1657, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1515, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 1022, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 259, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 366, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig SLEDConfig(name='gov_report', version=1.0.0, data_dir=None, data_files=None, description='\n@inproceedings{huang-etal-2021-efficient,\n    title = "Efficient Attentions for Long Document Summarization",\n    author = "Huang, Luyang  and\n      Cao, Shuyang  and\n      Parulian, Nikolaus  and\n      Ji, Heng  and\n      Wang, Lu",\n    booktitle = "Proceedings of the 2021 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies",\n    month = jun,\n    year = "2021",\n    address = "Online",\n    publisher = "Association for Computational Linguistics",\n    url = "https://aclanthology.org/2021.naacl-main.112",\n    doi = "10.18653/v1/2021.naacl-main.112",\n    pages = "1419--1436",\n    abstract = "The quadratic computational and memory complexities of large Transformers have limited their scalability for long document summarization. In this paper, we propose Hepos, a novel efficient encoder-decoder attention with head-wise positional strides to effectively pinpoint salient information from the source. We further conduct a systematic study of existing efficient self-attentions. Combined with Hepos, we are able to process ten times more tokens than existing models that use full attentions. For evaluation, we present a new dataset, GovReport, with significantly longer documents and summaries. Results show that our models produce significantly higher ROUGE scores than competitive comparisons, including new state-of-the-art results on PubMed. Human evaluation also shows that our models generate more informative summaries with fewer unfaithful errors.",\n}') 
doesn't have a 'verification_mode' key.
```
I have tried modifying the gov_report.json file to what I think it should be:
```
{
  "dataset_name": "ccdv/govreport-summarization",
  "dataset_config_name": "document",
  "max_source_length": 16384,
  "generation_max_length": 1024,
  "max_prefix_length": 0,
  "pad_prefix": false,
  "num_train_epochs": 10,
  "metric_names": ["rouge"],
  "metric_for_best_model": "rouge/geometric_mean",
  "greater_is_better": true
}
```
But I get the same "verification_mode" key error. I have seen that this verification_mode variable is new to hf. (Aside: when, in 'src/run.py',  I comment "verification_mode" out and replace it with the soon-to-deprecated "ignore_verifications=True")

So, returning to your original gov_report.jsn file, I find that the problem goes away when I comment it out and replace it with the soon-to-deprecated "ignore_verifications=True". But I think your gov_report.json file is pointing to the wrong dataset (tau/sled).

When I try to run the modified src/run.py on the correct gov_report.json file, I get:
```
```
Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1180, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 437, in main
    seq2seq_dataset = _get_dataset(data_args, model_args, training_args)
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 943, in _get_dataset
    seq2seq_dataset = load_dataset(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1657, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1515, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 1022, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 259, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 366, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig GovReportSummarizationConfig(name='document', version=1.0.0, data_dir=None, data_files=None, description='GovReport dataset for summarization, document') doesn't have a 'verification_mode' key.
```
However, then I get
```
Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1181, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 658, in main
    train_dataset = untokenized_train_dataset.map(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2092, in map
    return self._map_single(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/fingerprint.py", line 411, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2469, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2357, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2052, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1080, in preprocess_function
    if not isinstance(examples[input_column][0], str):
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 129, in __getitem__
    values = super().__getitem__(key)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'input'
```
This error, I recognize from trying to get your inference_example.py not working on the "ccdv/govreport-summarization" dataset. The culprit is:
```

```
Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1180, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 437, in main
    seq2seq_dataset = _get_dataset(data_args, model_args, training_args)
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 943, in _get_dataset
    seq2seq_dataset = load_dataset(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1657, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/load.py", line 1515, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 1022, in __init__
    super(GeneratorBasedBuilder, self).__init__(*args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 259, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/builder.py", line 366, in _create_builder_config
    raise ValueError(f"BuilderConfig {builder_config} doesn't have a '{key}' key.")
ValueError: BuilderConfig GovReportSummarizationConfig(name='document', version=1.0.0, data_dir=None, data_files=None, description='GovReport dataset for summarization, document') doesn't have a 'verification_mode' key.
```
However, then I get
```
Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1181, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 658, in main
    train_dataset = untokenized_train_dataset.map(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2092, in map
    return self._map_single(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/fingerprint.py", line 411, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2469, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2357, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2052, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/scratch/project_mnt/S0066/unlimiformer-mod/src/run.py", line 1080, in preprocess_function
    if not isinstance(examples[input_column][0], str):
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 129, in __getitem__
    values = super().__getitem__(key)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'input'
```
This error, I recognize from trying to get your inference_example.py working on the "ccdv/govreport-summarization" dataset. The culprit is (from the src/run.py file):
```
     if data_args.input_column is None: 
         input_column = "input"
 ```
 This is incompatible with the "ccdv/govreport-summarization" dataset which instead uses "report".
My understanding is that data_args takes its values either from the command line or from the gov_report.json file, right? Adding the following rows to the gov_report.json file fixes the problem:
```
"input_column="report",
"output_column="summary"
```

**Comment by patrickocal** [comment]
It's strange because I would expect the following lines from src/run.py
```
    # Preprocessing the datasets.
    # We need to tokenize inputs and targets.
    if training_args.do_train:
        column_names = seq2seq_dataset["train"].column_names
```
to pick up the column names from the ccdv/govreport-summarization dataset itself. Why doesn't it?

**Comment by patrickocal** [comment]
Would it not be best to have the basic src/run.py work with just two columns "input"/reports and "output"/summary? If you have one of those, could you please share it? I mean, this the most generic format and the GovReport dataset is your main example in the paper. Why do we need the extra columns eg input_prefix_column and "id"? From what I can tell, it seems like it's mainly to remove duplicates...

**Comment by patrickocal** [comment]
Anyway, I got it working by rewriting your deduplicate function and instead having it assign an "id" column. Most first-time users would be using this with a standard dataset such as ccdv/govreport-summarization. So no need for deduping. I also needed to change the column_names assignment within the run.py file. Seems like a bit of work is needed to make this more streamlined and accessible.

**Comment by patrickocal** [comment]
Ah okay, I now understand. In your original gov_report.json file:

  "dataset_name": "tau/sled",
  "dataset_config_name": "gov_report",
  "max_source_length": 16384,
  "generation_max_length": 1024,
  "max_prefix_length": 0,
  "pad_prefix": false,
  "num_train_epochs": 10,
  "metric_names": ["rouge"],
  "metric_for_best_model": "rouge/geometric_mean",
  "greater_is_better": true

Selects the gov_report dataset within  "tau/sled". Okay, that now makes sense. I will leave the above trail for others that go down the same rabbit hole. (I am still confused about what exactly an epoch is here. Why I don't see 17.5k when I run ccdv/govreport-summarization with "num_train_epochs": 1? Instead, I see 1000/8759, 2000/8759, ...) 

Finally, at the end of training, got the following error:
```
Traceback (most recent call last):
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/run.py", line 1181, in <module>
    main()
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/run.py", line 802, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/transformers/trainer.py", line 1984, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/transformers/trainer.py", line 2328, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/utils/custom_seq2seq_trainer.py", line 300, in evaluate
    output.metrics.update(self.compute_metrics(*eval_preds))
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/metrics/metrics.py", line 45, in __call__
    return self._compute_metrics(id_to_pred, id_to_labels)
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/metrics/metrics.py", line 60, in _compute_metrics
    result = metric(id_to_pred_decoded, id_to_labels_decoded, is_decoded=True)
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/metrics/metrics.py", line 27, in __call__
    return self._compute_metrics(id_to_pred, id_to_labels)
  File "/scratch/project_mnt/S0066/unlimiformer-orig/src/metrics/metrics.py", line 158, in _compute_metrics
    return self._metric.compute(**self.convert_from_map_format(id_to_pred, id_to_labels), **self.kwargs)
  File "/home/uqpocall/.conda/envs/unlimiformer/lib/python3.10/site-packages/datasets/metric.py", line 419, in compute
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/uqpocall/.cache/huggingface/metrics/bert_score/default/default_experiment-1-0.arrow'
```
Thanks!
